test the action giving all the validation errors before failing

diff --git a/.github/workflows/validate-fhir-hapi.yml b/.github/workflows/validate-fhir-hapi.yml
--- a/.github/workflows/validate-fhir-hapi.yml
+++ b/.github/workflows/validate-fhir-hapi.yml
@@ -23,6 +23,8 @@ env:
   SUSHI_ENABLED: true
   EXPECTED_FAILS: VALIDATION_CONFORMANCE_DOTNET VALIDATION_CONFORMANCE_JAVA VALIDATION_EXAMPLES_JAVA
   JAVA_SNAPSHOT_ENABLED: false 
+  OUTPUT_FAILURE: false
+  OUTPUT_FAILURE_MESSAGE: ""
 
 jobs:
   CI_EXAMPLES_VALIDATION:
@@ -151,15 +153,21 @@ jobs:
             find $PATH_TO_EXAMPLES -type f -name "*.json" -o -name "*.xml" | while read file; do
               echo "Validating $file..."
               if echo $EXPECTED_FAILS | grep -w -q VALIDATION_CONFORMANCE_DOTNET; then
-                fhir validate "$file"
+                VALIDATION_OUTPUT = $(fhir validate "$file" 2>&1)
               else
-                fhir validate "$file" --fail || EXIT_CODE=1
+                VALIDATION_OUTPUT = $(fhir validate "$file" --fail || EXIT_CODE=1)
+                if [ $? -ne 0 ]; then
+                  EXIT_CODE=1
+                  # Append the file name and validation output to the failure message
+                  OUTPUT_FAILURE_MESSAGE="${OUTPUT_FAILURE_MESSAGE}File: $file\nValidation Error: $VALIDATION_OUTPUT\n\n"
+                fi
               fi
             done
     
             # Exit with error if any validation failed
             if [ $EXIT_CODE -ne 0 ]; then
-              exit 1
+              OUTPUT_FAILURE = true
+              # exit 1
             fi
           fi
         shell: bash
@@ -269,3 +277,14 @@ jobs:
       - name: Cleanup
         if: always()
         run: rm -rf temp_folder
+
+  CHECK-ERRORS:
+    runs-on: ubuntu-latest
+    needs: CI_EXAMPLES_VALIDATION
+    steps:
+      - name: Check whether errors occurred 
+        run: |
+          if [ "$OUTPUT_FAILURE" = "true" ]; then
+            echo "$OUTPUT_FAILURE_MESSAGE"
+            exit 1
+          fi  
